env:
  num_node: 1
  node_ips: 
    - []
  tmp_path: <path to ml_tmp folder>
  data_path: <path to data folder>
  config_path: <path to /fraud_detection/configs/single-node folder>
  
data_preprocess:
  input_data_path: raw_data
  input_data_format: csv
  output_data_path: edge_data
  output_data_format: csv
  dp_config_file: data-preprocessing.yaml
  dp_framework: pandas
